### ISSUE TITLE
Mandatory 1

### ISSUE THREAD

**Issue by Moshizzl3** [SD-2-semester/DLS-semester-project#3]
# Tasks

- [ ] Form a working group and register your team in the excel file on our OneDrive: Excel sheet.
- [ ]  Come up with your own project based on the final project requirements.

## Define the system requirements:
- [ ] Functional
- [ ] Non-functional requirements
- [ ] Choose a project management strategy for your project.
- [ ] Choose your technology stack.
- [ ] Create GitHub repository / repositories for your project and provide the link / links in the excel
file on our OneDrive: Excel sheet.

## System architecture design

- [ ]  Draw the system architecture.
- [ ] Choose proper communication channels between the microservices and the outside world.
- [ ] Define the architectural patterns that you will follow (for example CQRS, Snapshot
pattern, etc.)
- [ ] Divide responsibilities within the team for the implementation of each part of the
system.

## Deployment strategy
- [ ] Investigate suitable cloud providers.
- [ ] Choose the cloud provider / providers for your system.
- [ ] Describe your CI/CD pipeline.
- [ ] Describe your testing strategy (though testing is not the main focus of this course).
- [ ] Investigate the options for logging and monitoring of your system in production.

## Documentation
- [ ] Define documentation strategy.
- [ ] Define versioning strategy: databases, APIs, code.

## Report
- [ ] Start writing the final project report (follow the required structure) - concentrate on the topics
from this assignment.

## Presentation
- [ ] Each working group will present their results during the class.
- [ ] Discussion
- [ ] Feedback - what to improve

## Delivery to Fronter before the deadline:
- [ ] Provide a link to your group GitHub repository / repositories.
- [ ] Upload your PowerPoint presentation.
